version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "support-rag-agent-dev"
resolve_s3 = true
resolve_image_repos = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "Stage=dev AgentModel=claude-opus-5"
